### ISSUE TITLE
kemono-error

### ISSUE THREAD

**Issue by naozhong2310** [ZIDOUZI/Kemono-Downloader-GUI#1]
{"Exception":{"ClassName":"System.IO.IOException","Message":"The response ended prematurely, with at least 72194102 additional bytes expected.","Data":{},"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)\r\n   at Kemono.Core.Services.FileDownload.Start()\r\n   at Kemono.Core.Services.FileDownload.Start()\r\n   at Kemono.Models.DownloadUi.Start()\r\n   at Kemono.Views.DownloadPage.DealWebFile(WebFile file)\r\n   at Kemono.Views.DownloadPage.<>c__DisplayClass36_0.<<DealPost>g__ForFile|0>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Kemono.Core.Models.EnumeratorHelper.DoWork[TSource,TResult](IEnumerator`1 iter, Func`2 run, Action`1 con)+MoveNext()\r\n   at Kemono.Core.Models.EnumeratorHelper.DoWork[TSource,TResult](IEnumerator`1 iter, Func`2 run, Action`1 con)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\r\n   at Kemono.Views.DownloadPage.DealPost(Post post)\r\n   at Kemono.Views.DownloadPage.DealPost(Post post)\r\n   at Kemono.Views.DownloadPage.<DealArtist>g__ForPost|35_0(Post post)\r\n   at Kemono.Core.Models.EnumeratorHelper.DoWork[TSource,TResult](IEnumerator`1 iter, Func`2 run, Action`1 con)+MoveNext()\r\n   at Kemono.Core.Models.EnumeratorHelper.DoWork[TSource,TResult](IEnumerator`1 iter, Func`2 run, Action`1 con)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\r\n   at Kemono.Views.DownloadPage.DealArtist(Artist artist)+MoveNext()\r\n   at Kemono.Views.DownloadPage.DealArtist(Artist artist)+MoveNext()\r\n   at Kemono.Views.DownloadPage.DealArtist(Artist artist)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\r\n   at Kemono.Views.DownloadPage.<StartDownload>g__ForArtist|34_0(Artist artist)\r\n   at Kemono.Views.DownloadPage.<StartDownload>g__ForArtist|34_0(Artist artist)\r\n   at Kemono.Core.Models.EnumeratorHelper.DoWork[TSource,TResult](IEnumerator`1 iter, Func`2 run, Action`1 con)+MoveNext()\r\n   at Kemono.Core.Models.EnumeratorHelper.DoWork[TSource,TResult](IEnumerator`1 iter, Func`2 run, Action`1 con)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()\r\n   at Kemono.Views.DownloadPage.StartDownload()\r\n   at Kemono.Views.DownloadPage.StartDownload()\r\n   at Kemono.Views.DownloadPage.Download_OnClick(Object sender, RoutedEventArgs e)\r\n   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)\r\n   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":"System.Net.Http","WatsonBuckets":null},"Handled":false,"Message":"The response ended prematurely, with at least 72194102 additional bytes expected."}

**Comment by ZIDOUZI** [comment]
请更新[最新版](https://github.com/ZIDOUZI/Kemono-Downloader-GUI/releases/tag/1.2.14.0)查看是否还有异常
